In [1]:
import numpy as hah
arr=hah.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])

In [2]:
#Original array
print("Original array:\n",arr)


Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [3]:
#return every other rows
print("\nEvery other rows:arr[0:3:2]:\n",arr[0:3:2])



Every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [4]:
#slicing array
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:arr[:2,:3]:\n",temp)



Array with first 2 rows and 3 columns:arr[:2,:3]:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [5]:
#integer array indexing example
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1),"
     "(3,0):\n",temp)



Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [6]:
#boolean array indexing example
cond=arr>2


In [7]:
#cond is a bollean array
temp=arr[cond]
print("\nElements greater than 2:\n",temp)



Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [8]:
#Return every other element from the entire array:
arr=hah.array([1,2,3,4,5,6,7])
print("\noriginal array:",arr)
print("\nReturn every other element from the entire array:arr[::2]:",arr[::2])



original array: [1 2 3 4 5 6 7]

Return every other element from the entire array:arr[::2]: [1 3 5 7]


In [9]:
#joining two array
arr1=hah.array([1,2,3])
arr2=hah.array([4,5,6])
arr=hah.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)



Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [10]:
#Horizontal join
arr=hah.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)



Horizontal joining:
 [1 2 3 4 5 6]


In [11]:
#Vertical join
arr=hah.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [12]:
#Depth join
arr=hah.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [13]:
#splitting array
arr=hah.array([1,2,3,4,5,6])
newarr=hah.array_split(arr,3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
#Display splitted array in another form
print("\nsplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


splitted array in another form:

[1 2]
[3 4]
[5 6]
