In [1]:
import numpy as hah
a=hah.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import numpy as hah
a=hah.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
b=hah.zeros((3,4))
print("THE ELEMENT IN ARRAY IS",b)
c=hah.full((3,3),7)
print(c)
d=hah.random.random((3,3))
print(d)
e=hah.arange(10,99,15)
print(e)
a.reshape(4,4)
print(a)
f=a.flatten()
print(f)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
g=a.astype('f')
print(g)
print(a)
print(a[0:3:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
THE ELEMENT IN ARRAY IS [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.42304425 0.52441804 0.47493733]
 [0.74837347 0.09000861 0.71190394]
 [0.20419018 0.78360556 0.49728437]]
[10 25 40 55 70 85]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
2
(4, 4)
16
int32
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
